name: Deploy to Github Pages

on:
   push: 
       branches:
            -master
jobs:
   deploy:
   runs-on: ubuntu_latest

   steps:
   - name: Checkout Repository
   uses: action/checkout@v2

   -name: Setup node.js
   user: actions/setup-node@v2
   whit:
   node-version: 18

   name: Install Dependencies
     run: npm install

   name: Build and Deploy
   run: |
        nmp run build --base-href=/pages-my-aplicacion/
        npx angular-cli-ghpages --dir/pages